services:
  asterisk:
    build: ./voip
    container_name: asterisk_engine
    network_mode: "host"
    cap_add:
      - SYS_PTRACE
      - NET_ADMIN
    volumes:
      - ./voip/config/pjsip.conf:/etc/asterisk/pjsip.conf
      - ./voip/config/extensions.conf:/etc/asterisk/extensions.conf
      - ./voip/config/http.conf:/etc/asterisk/http.conf
      - ./voip/config/rtp.conf:/etc/asterisk/rtp.conf
      - ./voip/keys:/etc/asterisk/keys
    restart: always
